sudo: required

services:
  - docker

env:
  - TAG=0.1

script:
  - exec docker build -t nxos/nxos:$TAG .

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push luislavaire/nxos
